port: :8080
tgToken: 7727116717:AAH31RbD5ygRkuWGO1EaCcfKybAoirykxaY
nsFeed: https://rss.nodeseek.com
adminId: 415257783
fetchTimeInterval: 10s
subscribes:
    - name: test
      chatId: -989876
      keywords:
        - test
      status: "on"
      type: channel

