tgToken: 7727116717:AAH31RbD5ygRkuWGO1EaCcfKybAoirykxaY
tgChatId: 0
nsFeed: https://rss.nodeseek.com/
alterChatId: 0
channels:
    - name: test
      chatId: 9999
      keywords:
        - claw
        - ggy
        - pikpak
      status: ""

    - name: "NS通知\U0001F4E2"
      chatId: -1002354873512
      keywords: []
      status: ""
