tgToken: 7727116717:AAH31RbD5ygRkuWGO1EaCcfKybAoirykxaY
tgChatId: 0
nsFeed: https://rss.nodeseek.com/
alterChatId: 0
channels:
    - name: hellomryee
      chatId: 415257783
      keywords:
        - pqs
      status: "on"
      type: chat
