name: Release

on:
  push:
    tags:
      - 'v*' # 触发条件：推送以 v 开头的tag

env:
  APP_NAME: ns-feed-bot
  DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 获取完整的git历史用于版本号

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binaries
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          ./build.sh --docker --repo=${{ secrets.DOCKER_USERNAME }} --version=$VERSION

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
